name: record_platform_interface
description: A common interface for the record package to call dedicated platforms with method channel.
homepage: https://github.com/llfbandit/record/tree/master/record_platform_interface
version: 1.0.2
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_lints:
    git: https://github.com/kumsumit/flutter_lints.git
